using System.IO; // For Path.Combine
using System;
using Sharpmake; // Contains the entire Sharpmake object library.

namespace Inferno
{
    // Represents the project that will be generated by Sharpmake and that contains
    // the sample C++ code.
    [Generate]
    public class CoreLib : InfernoLib
    {
        public CoreLib() : base("core")
        {
            SourceRootPath = Defines.Paths.INFERNO_CORE_SRC;
           
        }

         public override void ConfigureAll(Project.Configuration conf, Target target)
        {
            base.ConfigureAll(conf, target);

            conf.IncludePaths.Add(Defines.Paths.INFERNO_CORE_INC);
            conf.IncludePaths.Add(Path.Combine(Defines.Paths.INFERNO_THIRD_PARTY, "spdlog/include"));
        }
    }
}