using System.IO; // For Path.Combine
using Sharpmake; // Contains the entire Sharpmake object library.

namespace Inferno
{
    // Represents the project that will be generated by Sharpmake and that contains
    // the sample C++ code.
    [Generate]
    public class GraphicsLib : InfernoLib
    {
        public GraphicsLib() : base("graphics")
        {
            SourceRootPath = Defines.Paths.INFERNO_GRAPHICS_SRC;
        }
    }
}